### ISSUE TITLE
undefined is not an object (evaluating 'globalOrWindow.navigator.userAgent.toString')

### ISSUE THREAD

**Issue by muzzamil76** [magicbell-io/react-headless#206] opened 2022-06-24 09:41 UTC
I am having this issue when wrapping my App with MagicBellProvider.

@smeijer Please help

**Comment by smeijer** [comment] 2022-06-24 09:59
Hi @muzzamil76 , that doesn't sound familiar to me. Can you please share a stack trace of the error?

**Comment by Malik-Abdulaziz-Akbar** [comment] 2022-06-28 12:22
@smeijer Steps to reproduce this issue:

- Make a new react-native app using the Typescript template (`npx react-native init MyApp --template react-native-template-typescript`)
- Install @magicbell/react-headless (version 4.0.3 in my case)
- Wrapping my application with magicbell provider (like shown in image below)
<img width="483" alt="Screenshot 2022-06-28 at 5 09 55 PM" src="https://user-images.githubusercontent.com/37701187/176175060-89c9cbd1-6f44-445b-a81b-d700d7f59b66.png">
- Running the application on android device `npx react-native run-android`


I got a total of 4 errors

Stack trace of all four errors:
<img width="1339" alt="Screenshot 2022-06-28 at 5 15 09 PM" src="https://user-images.githubusercontent.com/37701187/176176370-c0ff8d62-9a3a-4985-893c-89d0fb2f3243.png">

Additional Details:

- Node version 18.2.0
- Npm Version 8.9.0
- Package.json dependencies
<img width="693" alt="Screenshot 2022-06-28 at 5 19 52 PM" src="https://user-images.githubusercontent.com/37701187/176177260-28fc3897-c893-48ed-b3c0-c9e445f256f5.png">

**Comment by smeijer** [comment] 2022-06-28 12:29
Got it. Thanks for the stacktrace! So it's a problem with Ably not running in a browser. I'll look into it.

**Comment by smeijer** [comment] 2022-06-29 07:43
I'm not sure where it goes wrong in your code, but I've created a codesandbox here that shows that the SDK can be used using react-native (web). Does that help?

https://codesandbox.io/s/react-native-magicbell-react-headless-oxdzcc?file=/src/App.js

**Comment by Malik-Abdulaziz-Akbar** [comment] 2022-06-29 07:57
Did you try to set up a react-native application as I mentioned above?

**Comment by muzzamil76** [comment] 2022-06-30 09:15
Hi @smeijer whats's the status ? I still not able to run in React-native mobile application.Still the same issue as mentioned by @Malik-Abdulaziz-Akbar above.

i.e
undefined is not an object (evaluating 'globalOrWindow.navigator.userAgent.toString')

**Comment by smeijer** [comment] 2022-06-30 12:00
@Malik-Abdulaziz-Akbar, Yes, I've taken the steps as you mentioned above, and I can confirm that `@magicbell/react-headless` works as expected, and is compatible with react-native. I do not experience the issues that you've mentioned. 

@muzzamil76 , the status is that I've created a reproduction, and confirmed the working of the SDK. I'm afraid I can't help you any further on this issue at this moment. I'm closing this ticket, as I can't reproduce this in the latest version of our SDK.

If you need further assistance, [please join us on Slack](https://magicbell.com/slack)

![image](https://user-images.githubusercontent.com/1196524/176670678-a5aba79b-a38b-44bc-a94b-7a88fa4bfdd9.png)

**Closed by smeijer** 2022-06-30 12:00 UTC

**Comment by Malik-Abdulaziz-Akbar** [comment] 2022-06-30 12:24
@smeijer  it would be very helpful if you can share the github repository link (Not the codesandbox link) for the above example.
